export const Routes = {
  Root: 'Root',
  Home: 'Home',
  Login: 'Login',
  Drawer: 'Drawer',
  About: 'About',
  Author: 'Author',
  Created: 'Created',
  Landing: 'Landing',
  Feedback: 'Feedback',
  Profile: 'Profile',
  Register: 'Register',
  History: 'History',
  Favourite: 'Favourite',
  QuizTest: 'QuizTest',
  QuizResult: 'QuizResult',
  QuizPractice: 'QuizPractice',
  Questionnaire: 'Questionnaire',
  QuestionnaireLevel: 'QuestionnaireLevel',
};
